#!/usr/bin/env bash
[ ! -e "$FREESURFER_HOME" ] && echo "error: freesurfer has not been properly sourced" && exit 1
[ ! -e "$FS_PYTHON_DEV" ] && echo "error: dev freesurfer has not been properly sourced" && exit 1
[ ! -e "$PHOTO_RECON_HOME" ] && echo "error: photovolume has not been properly sourced" && exit 1
exec $PHOTO_RECON_HOME/code/Segmentation/bashdevfspython $FS_PYTHON_DEV/samseg/run_samseg "$@"